name : Deploy Lambda Function

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.12'
      - name: Install AWS CLI and SAM CLI
        run: |
          pip install awscli
          pip install aws-sam-cli
      - name: Package Lambda Function
        run: |
           zip getuser_lambda_function.zip getuser_lambda_function.py
           zip adduser_lambda_function.zip adduser_lambda_function.py
      - name: Deploy Lambda Function
        run: |
           aws lambda create-function --function-name GetUserFunction1 --runtime python3.12 --handler getuser_lambda_function.lambda_handler --role arn:aws:iam::982044534919:role/mylambdarole --zip-file fileb://getuser_lambda_function.zip
           aws lambda create-function --function-name AddUserFunction2 --runtime python3.12 --handler adduser_lambda_function.lambda_handler --role arn:aws:iam::982044534919:role/mylambdarole --zip-file fileb://adduser_lambda_function.zip
           aws dynamodb create-table \
           --table-name MyTable \
           --attribute-definitions \
           AttributeName=Id,AttributeType=S \
           AttributeName=Name,AttributeType=S \
           # Add more attributes as needed
           --key-schema \
           AttributeName=Id,KeyType=HASH \
           # Add more key attributes as needed
           --provisioned-throughput \
           ReadCapacityUnits=5,WriteCapacityUnits=5 \
           # Adjust read and write capacity units as needed
           --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  # Change this to your desired AWS region
