name : Deploy Lambda Function

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.12'
      
      - name: Install AWS CLI and SAM CLI
        run: |
          pip install awscli
          pip install aws-sam-cli

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ AKIAXYKJP7BZLXNL4UEE }}
          aws configure set aws_secret_access_key ${{ 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 }}
          aws configure ser default.region eu-north-1


      - name: Build and Deploy Lambda Function
        run: |
          sam build
          echo "y" | sam deploy --stack-name LambdaFuncStack --region eu-north-1 --resolve-s3 --confirm-changeset false --capabilities CAPABILITY_IAM
          
