name : Deploy Lambda Function

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.12'
      - name: Install AWS CLI and SAM CLI
        run: |
          pip install awscli
          pip install aws-sam-cli
      - name: Package Lambda Function
        run: |
           zip getuser_lambda_function.zip getuser_lambda_function.py
           zip adduser_lambda_function.zip adduser_lambda_function.py
      - name: Deploy Lambda Function
        run: |
           aws lambda create-function --function-name GetUserFunction1 --runtime python3.12 --handler getuser_lambda_function.lambda_handler --role arn:aws:iam::982044534919:role/mylambdarole --zip-file fileb://getuser_lambda_function.zip
           aws lambda create-function --function-name AddUserFunction2 --runtime python3.12 --handler adduser_lambda_function.lambda_handler --role arn:aws:iam::982044534919:role/mylambdarole --zip-file fileb://adduser_lambda_function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  # Change this to your desired AWS region
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create DynamoDB table
        run: |
         aws dynamodb create-table \
         --table-name MyTable \
         --attribute-definitions \
           AttributeName=Id,AttributeType=S \
           AttributeName=Name,AttributeType=S \
         --key-schema \
           AttributeName=Id,KeyType=HASH \
           AttributeName=Name,KeyType=RANGE \
         --provisioned-throughput \
           ReadCapacityUnits=5,WriteCapacityUnits=5 \
         --region us-east-1
