name : Deploy Lambda Function

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.12'
      - name: Install AWS CLI and SAM CLI
        run: |
          pip install awscli
          pip install aws-sam-cli
      - name: Deploy Lambda Function
        run: aws lambda create-function --function-name MyLambdaFunction --runtime python3.12 --handler getuser_lambda_function.lambda_handler
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  # Change this to your desired AWS region
